### ISSUE TITLE
ZMK key generation failed

### ISSUE THREAD

**Issue by zeeshan949** [snowch/hsm-guide#4]
Thank you for your hsm-guide book this is very helpful understanding working of HSM and also work with Thales Simulator. After following your guide and tried to generate ZMK with simulator console. But when send FK command to console and enter pre generated ZMK components console give error "INVALID KEY".

Thales simulator version 0.9.6
OS Windows 8.1

See console logs

Connected - Type in commands followed by ENTER.
GC
Key length [1,2,3]: 2
Key Type: 000
Key Scheme: U
Clear Component: 0275 76E5 07A7 CB3B FB32 0D07 40BA DC51 
Encrypted Component: U FE61 44E1 4EB2 BC48 4888 7E19 A592 D7B3 
Key check value: E341 91
GC
Key length [1,2,3]: 2
Key Type: 000
Key Scheme: U
Clear Component: 616E 32A8 F7CB 0461 20A7 B583 1007 A273 
Encrypted Component: U 0E40 2740 82B5 0098 5051 B8B8 1070 E5A0 
Key check value: 2605 25
GC
Key length [1,2,3]: 2
Key Type: 000
Key Scheme: U
Clear Component: 191A 547C 0B3B 045E AB8C 3E51 92D0 15DC 
Encrypted Component: U E4EF C72D 2EB6 FC0C 5C8B 9FFC 760E 80F2 
Key check value: 39E9 9C

FK
Key length [1,2,3]: 2
Key Type: 000
Key Scheme: U
Component type [X,H,E,S]: E
Enter number of components (2-9): 3
Enter component #1: U FE61 44E1 4EB2 BC48 4888 7E19 A592 D7B3
INVALID KEY

**Comment by erfanhossainshoaib** [comment]
I have a problem to import key using ZMK.
Generated ZMK successfully from Thales Console and KCV is matched.
But can't import PEK by using IK command.

Generated ZMK : U09C26D8449DFB036466CBE693CA244A0
PEK : 56C8DACE4447FFC02D9F385D67072A88
KCV : 142623

Sending command: HeadA6002U09C26D8449DFB036466CBE693CA244A0X56C8DACE4447FFC02D9F385D67072A88U00
Response: **HeadA726**, Error code : 26 means Invalid Key Scheme

Tried with below commands also but same result. Sending commands are

HeadA6002U09C26D8449DFB036466CBE693CA244A0U56C8DACE4447FFC02D9F385D67072A88U00
HeadA6002U09C26D8449DFB036466CBE693CA244A0T56C8DACE4447FFC02D9F385D67072A88U00
HeadA6002U09C26D8449DFB036466CBE693CA244A0Z56C8DACE4447FFC02D9F385D67072A88U00
HeadA6002U09C26D8449DFB036466CBE693CA244A0E56C8DACE4447FFC02D9F385D67072A88U00
HeadA6002U09C26D8449DFB036466CBE693CA244A0S56C8DACE4447FFC02D9F385D67072A88U00

Response are same for all command. Response is **HeadA726**
