### ISSUE TITLE
PIN Block Genration

### ISSUE THREAD

**Issue by zeeshan949** [snowch/hsm-guide#5]
Hi,

After going through Key generation can you guide me about PIN Block generation on remote site.
I have read thales documentation but unable to understand following operation.

Things required for PIN block generation.
Plain ZPK/TPK
Encrypted ZPK/TPK

how to generate plain and encrypted ZPK/TPK under ZMK/TMK?

**Comment by snowch** [comment]
Thanks @zeeshan949.  Sorry for the delay in responding, I haven't had a chance to work on this product.  Please send me patch requests if you have any improvements.
