### ISSUE TITLE
Some more documentation that you could use.

### ISSUE THREAD

**Issue by chhil** [snowch/hsm-guide#6]
I have a pdf  titled "HSM and Thales Basics using the Thales
Simulator" at https://groups.google.com/d/msg/jpos-users/KsDT_DAQwn8/wW4vivhY3WcJ
You may find some useful things in there that you could use.

-chhil

**Comment by snowch** [comment]
Thanks @chhil - sorry for the delay in answering.  I haven't had chance to look at this project in a while.  Feel free to send me patches if you have some improvements.
